module.exports = {
	darkMode: 'class',
	theme: {
		fontSize: {
		  xs: 'var(--text-xs)',
		  sm: 'var(--text-sm)',
		  base: 'var(--text-base)',
		  lg: 'var(--text-lg)',
		  xl: 'var(--text-xl)',
		  '2xl': 'var(--text-2xl)',
		  '3xl': 'var(--text-3xl)',
		  '4xl': 'var(--text-4xl)',
		  '5xl': 'var(--text-5xl)',
		  '6xl': 'var(--text-6xl)',
		  '7xl': 'var(--text-7xl)',
		  '8xl': 'var(--text-8xl)',
		  '9xl': 'var(--text-9xl)',
		},
		borderWidth: {
		  '0': '0',
		  '1': 'var(--border-1)',	
		  DEFAULT: 'var(--border-1)',
		  '2': 'var(--border-2)',
		  '3': 'var(--border-3)',
		  '4': 'var(--border-4)',
		  '5': 'var(--border-5)',
		  '6': 'var(--border-6)',
		  '7': 'var(--border-7)',
		  '8': 'var(--border-8)',
		  'custom-1': 'var(--border-custom-1)',
		  'custom-2': 'var(--border-custom-2)',
		},
		 borderRadius: {
		  'none': '0',
		  'sm': 'var(--radius-sm)',
		  'bs': 'var(--radius-bs)',
		  DEFAULT: 'var(--radius-bs)',
		  'md': 'var(--radius-md)',
		  'lg': 'var(--radius-lg)',
		  'xl': 'var(--radius-xl)',
		  '2xl': 'var(--radius-2xl)',
		  '3xl': 'var(--radius-3xl)',
		  'full': '9999px',
		},
		boxShadow: {
			'sm': 		'var(--shadow-sm)',
			'bs': 		'var(--shadow-bs)',
			'md': 		'var(--shadow-md)',
			'lg': 		'var(--shadow-lg)',
			'xl': 		'var(--shadow-xl)',
			'2xl': 		'var(--shadow-2xl)',
			'3xl': 		'var(--shadow-3xl)',
			'inset':	'var(--shadow-inset)',
		  },
		 letterSpacing: {
			 tightest: 	'var(--leading-tightest)',
			 tighter: 	'var(--leading-tighter)',
			 tight: 	'var(--leading-tight)',
			 normal: 	'var(--leading-normal)',
			 wide: 		'var(--leading-wide)',
			 wider: 	'var(--leading-wider)',
			 widest: 	'var(--leading-widest)',
		},
		
		extend: {
			fontFamily: {				
				'body': ['Open Sans', 'Arial', 'sans-serif'],
				'display': ['Helvetica condensed', 'Arial', 'sans-serif'],
			},
			colors: {
				"primary": {
				  50: 'var(--primary-l-5)',
				  100: 'var(--primary-l-4)',
				  200: 'var(--primary-l-3)',
				  300: 'var(--primary-l-2)',
				  400: 'var(--primary-l-1)',
				  DEFAULT: 'var(--primary)',
				  500: 'var(--primary)',
				  600: 'var(--primary-d-1)',
				  700: 'var(--primary-d-2)',
				  800: 'var(--primary-d-3)',
				  900: 'var(--primary-d-4)',
				},
				"secondary": {
				  50: 'var(--secondary-l-5)',
				  100: 'var(--secondary-l-4)',
				  200: 'var(--secondary-l-3)',
				  300: 'var(--secondary-l-2)',
				  400: 'var(--secondary-l-1)',
				  DEFAULT: 'var(--secondary)',
				  500: 'var(--secondary)',
				  600: 'var(--secondary-d-1)',
				  700: 'var(--secondary-d-2)',
				  800: 'var(--secondary-d-3)',
				  900: 'var(--secondary-d-4)',
				}
			},
			
			 aspectRatio: {
				'landscape': '4 / 3',
				'portrait': '3 / 4', 
				'ultrawide': '18 / 5',
				'golden': '1.6180 / 1',
				'rrss': '1.91 / 1',
			  },
			
			spacing: {
				'sp-2xs':  	'var(--sp-2xs)',
				'sp-xs':	'var(--sp-xs)',
				'sp-sm': 	'var(--sp-sm)',
				'sp': 		'var(--sp)',
				'sp-lg':	'var(--sp-lg)',
				'sp-xl': 	'var(--sp-xl)',
				'sp-2xl': 	'var(--sp-2xl)',
				'sp-3xl': 	'var(--sp-3xl)',
				'sp-4xl': 	'var(--sp-4xl)',
			  },
			lineHeight: {
				'leading-none': 	'var(--leading-none)',
				'leading-tight': 	'var(--leading-tight)',
				'leading-snug': 	'var(--leading-snug)',
				'leading-normal': 	'var(--leading-normal)',
				'leading-relaxed': 	'var(--leading-relaxed)',
				'leading-loose': 	'var(--leading-loose)',
			  },

			// ...
		},
	},
	plugins: [
	],
	corePlugins: {
		preflight: true,
	}
}
